/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ASUS_PC
 */
public class AreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePanel
     */
    public AreaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArea = new javax.swing.JTable();
        btnGotoCentre = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Area Code:");
        add(jLabel1);
        jLabel1.setBounds(190, 50, 80, 20);

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        add(txtCode);
        txtCode.setBounds(280, 50, 140, 20);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/red-search-icon.png"))); // NOI18N
        btnSearch.setText("  Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(460, 50, 110, 33);

        btnAll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAll.setText("Show All");
        add(btnAll);
        btnAll.setBounds(130, 130, 90, 30);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(240, 130, 90, 30);

        btnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDel.setText("Delete");
        add(btnDel);
        btnDel.setBounds(460, 130, 90, 30);

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        add(btnEdit);
        btnEdit.setBounds(350, 130, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Area Name:");
        add(jLabel2);
        jLabel2.setBounds(190, 90, 80, 20);
        add(txtName);
        txtName.setBounds(280, 90, 140, 20);

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setRequestFocusEnabled(false);

        tblArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Area Code", "Area Name"
            }
        ));
        jScrollPane2.setViewportView(tblArea);

        add(jScrollPane2);
        jScrollPane2.setBounds(120, 180, 492, 226);

        btnGotoCentre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGotoCentre.setText("Go to Centre");
        btnGotoCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGotoCentreActionPerformed(evt);
            }
        });
        add(btnGotoCentre);
        btnGotoCentre.setBounds(570, 450, 111, 35);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey-Background-39.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 740, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGotoCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGotoCentreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGotoCentreActionPerformed

    public JTable getTblArea() {
        return tblArea;
    }

    public void setTblArea(JTable tblArea) {
        this.tblArea = tblArea;
    }

    public JTextField getTxtCode() {
        return txtCode;
    }

    public void setTxtCode(JTextField txtCode) {
        this.txtCode = txtCode;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public void setTxtName(JTextField txtName) {
        this.txtName = txtName;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }
    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JButton getBtnAll() {
        return btnAll;
    }

    public JButton getBtnDel() {
        return btnDel;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }    
    public JButton getBtnGoto() {
        return btnGotoCentre;
    }    
    
    public void addBtnAreaListener(ActionListener log) {
        btnAdd.addActionListener(log);
        btnAll.addActionListener(log);
        btnDel.addActionListener(log);
        btnEdit.addActionListener(log);
        btnSearch.addActionListener(log);
        btnGotoCentre.addActionListener(log);
    }        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGotoCentre;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblArea;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
