/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ASUS_PC
 */
public class CentrePanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePanel
     */
    public CentrePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCentre = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Centre Id:");
        add(jLabel1);
        jLabel1.setBounds(76, 47, 50, 14);
        add(txtId);
        txtId.setBounds(390, 44, 110, 20);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(518, 43, 65, 23);

        btnAll.setText("Show All");
        add(btnAll);
        btnAll.setBounds(446, 284, 73, 23);

        btnAdd.setText("Add");
        add(btnAdd);
        btnAdd.setBounds(529, 284, 71, 23);

        btnDel.setText("Delete");
        add(btnDel);
        btnDel.setBounds(688, 284, 71, 23);

        btnEdit.setText("Edit");
        add(btnEdit);
        btnEdit.setBounds(606, 284, 72, 23);
        add(txtName);
        txtName.setBounds(390, 84, 110, 20);

        jLabel2.setText("Centre Name:");
        add(jLabel2);
        jLabel2.setBounds(76, 84, 67, 14);

        tblCentre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Centre ID", "Centre Name"
            }
        ));
        jScrollPane2.setViewportView(tblCentre);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 325, 835, 182);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey-Background-39.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(-5, -6, 880, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed
    

    public JTable getTblCentre() {
        return tblCentre;
    }

    public void setTblCentre(JTable tblCentre) {
        this.tblCentre = tblCentre;
    }   

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public void setTxtName(JTextField txtName) {
        this.txtName = txtName;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JButton getBtnAll() {
        return btnAll;
    }

    public JButton getBtnDel() {
        return btnDel;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }
    
    public void addBtnCentreListener(ActionListener log) {
        btnAdd.addActionListener(log);
        btnAll.addActionListener(log);
        btnDel.addActionListener(log);
        btnEdit.addActionListener(log);
        btnSearch.addActionListener(log);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCentre;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
