/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author DH
 */
public class ExportToExcelPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExportToExcelPanel
     */
    public ExportToExcelPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        AreaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArea = new javax.swing.JTable();
        btnAreaExportToExcel = new javax.swing.JButton();
        CentrePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCentre = new javax.swing.JTable();
        btnCentreExportToExcel = new javax.swing.JButton();
        EmployeePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnEmployeeExportToExcel = new javax.swing.JButton();

        tblArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblArea);

        btnAreaExportToExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAreaExportToExcel.setText("Export to Excel");
        btnAreaExportToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaExportToExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AreaPanelLayout = new javax.swing.GroupLayout(AreaPanel);
        AreaPanel.setLayout(AreaPanelLayout);
        AreaPanelLayout.setHorizontalGroup(
            AreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAreaExportToExcel)
                .addContainerGap())
        );
        AreaPanelLayout.setVerticalGroup(
            AreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAreaExportToExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        tabPanel.addTab("tab1", AreaPanel);

        tblCentre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCentre);

        btnCentreExportToExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCentreExportToExcel.setText("Export to Excel");
        btnCentreExportToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentreExportToExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CentrePanelLayout = new javax.swing.GroupLayout(CentrePanel);
        CentrePanel.setLayout(CentrePanelLayout);
        CentrePanelLayout.setHorizontalGroup(
            CentrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CentrePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCentreExportToExcel)
                .addContainerGap())
        );
        CentrePanelLayout.setVerticalGroup(
            CentrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentrePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCentreExportToExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        tabPanel.addTab("tab2", CentrePanel);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblEmployee);

        btnEmployeeExportToExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEmployeeExportToExcel.setText("Export to Excel");
        btnEmployeeExportToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeExportToExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEmployeeExportToExcel)
                .addContainerGap())
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmployeeExportToExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        tabPanel.addTab("tab3", EmployeePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );

        tabPanel.getAccessibleContext().setAccessibleName("tab 1");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaExportToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaExportToExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAreaExportToExcelActionPerformed

    private void btnCentreExportToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentreExportToExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCentreExportToExcelActionPerformed

    private void btnEmployeeExportToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeExportToExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeExportToExcelActionPerformed

    public JPanel getAreaPanel() {
        return AreaPanel;
    }

    public void setAreaPanel(JPanel AreaPanel) {
        this.AreaPanel = AreaPanel;
    }

    public JPanel getCentrePanel() {
        return CentrePanel;
    }

    public void setCentrePanel(JPanel CentrePanel) {
        this.CentrePanel = CentrePanel;
    }

    public JPanel getEmployeePanel() {
        return EmployeePanel;
    }

    public void setEmployeePanel(JPanel EmployeePanel) {
        this.EmployeePanel = EmployeePanel;
    }

    public JButton getBtnAreaExportToExcel() {
        return btnAreaExportToExcel;
    }

    public void setBtnAreaExportToExcel(JButton btnAreaExportToExcel) {
        this.btnAreaExportToExcel = btnAreaExportToExcel;
    }

    public JButton getBtnCentreExportToExcel() {
        return btnCentreExportToExcel;
    }

    public void setBtnCentreExportToExcel(JButton btnCentreExportToExcel) {
        this.btnCentreExportToExcel = btnCentreExportToExcel;
    }

    public JButton getBtnEmployeeExportToExcel() {
        return btnEmployeeExportToExcel;
    }

    public void setBtnEmployeeExportToExcel(JButton btnEmployeeExportToExcel) {
        this.btnEmployeeExportToExcel = btnEmployeeExportToExcel;
    }

    public JTabbedPane getTabPanel() {
        return tabPanel;
    }

    public void setTabPanel(JTabbedPane tabPanel) {
        this.tabPanel = tabPanel;
    }

    public JTable getTblArea() {
        return tblArea;
    }

    public void setTblArea(JTable tblArea) {
        this.tblArea = tblArea;
    }

    public JTable getTblCentre() {
        return tblCentre;
    }

    public void setTblCentre(JTable tblCentre) {
        this.tblCentre = tblCentre;
    }

    public JTable getTblEmployee() {
        return tblEmployee;
    }

    public void setTblEmployee(JTable tblEmployee) {
        this.tblEmployee = tblEmployee;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaPanel;
    private javax.swing.JPanel CentrePanel;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JButton btnAreaExportToExcel;
    private javax.swing.JButton btnCentreExportToExcel;
    private javax.swing.JButton btnEmployeeExportToExcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tblArea;
    private javax.swing.JTable tblCentre;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables
}
