/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;

/**
 *
 * @author ASUS_PC
 */
public class UserPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    public UserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtOPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtNPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtCNPass = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Hello!");
        add(jLabel4);
        jLabel4.setBounds(270, 60, 100, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Old Password:");
        add(jLabel1);
        jLabel1.setBounds(160, 120, 100, 14);

        txtOPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOPassActionPerformed(evt);
            }
        });
        add(txtOPass);
        txtOPass.setBounds(310, 120, 170, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("New Password:");
        add(jLabel2);
        jLabel2.setBounds(160, 160, 110, 14);

        txtNPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNPassActionPerformed(evt);
            }
        });
        add(txtNPass);
        txtNPass.setBounds(310, 160, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Re-enter Password");
        add(jLabel3);
        jLabel3.setBounds(160, 200, 120, 20);
        add(txtCNPass);
        txtCNPass.setBounds(310, 200, 170, 20);

        btnChangePass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnChangePass.setText("Change Password");
        add(btnChangePass);
        btnChangePass.setBounds(260, 250, 140, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey-Background-39.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(-4, -4, 860, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOPassActionPerformed

    private void txtNPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNPassActionPerformed
    
     public JPasswordField getTxtOPass() {
        return txtOPass;
    }

    public void setTxtOPass(JPasswordField txtOPass) {
        this.txtOPass = txtOPass;
    }

     public JPasswordField getTxtNPass() {
        return txtNPass;
    }

    public void setTxtNPass(JPasswordField txtNPass) {
        this.txtNPass = txtNPass;
    }

     public JPasswordField getTxtCNPass() {
        return txtCNPass;
    }

    public void setTxtCNPass(JPasswordField txtCNPass) {
        this.txtCNPass = txtCNPass;
    }

    
     public JButton getBtnChangePass() {
        return btnChangePass;
    }

    public void setBtnChangepass(JButton btnChangePass) {
        this.btnChangePass= btnChangePass;
    }

    public void addBtnUserListener(ActionListener log) {
        btnChangePass.addActionListener(log);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtCNPass;
    private javax.swing.JPasswordField txtNPass;
    private javax.swing.JPasswordField txtOPass;
    // End of variables declaration//GEN-END:variables
}
